### ISSUE TITLE
Does not work since yesterday

### ISSUE THREAD

**Issue by Kopr1975** [BOT-HAT/Smm-Job-Bot#2]
The bot fails on line with json.loads

**Comment by Zebraslive** [comment]
try this one 
https://github.com/Zebraslive/Smm-Job-Bot-Node

**Comment by Zebraslive** [comment]
> The bot fails on line with json.loads

try this one 
https://github.com/Zebraslive/Smm-Job-Bot-Node

**Comment by Kopr1975** [comment]
Hello, does anyone has working script for node.js..?...The one that I have caused that I received penalty status...Thank you very much.
